/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Firebase scripts need to be imported via importScripts in the SW
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging-compat.js');

self.skipWaiting();
clientsClaim();

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Initialize Firebase
const firebaseConfig = {
  apiKey: "AIzaSyCnzDtAhfGJtCps33cOXcjMqQ1QCnoPEdU",
  authDomain: "gastosapp-druizinho.firebaseapp.com",
  projectId: "gastosapp-druizinho",
  storageBucket: "gastosapp-druizinho.firebasestorage.app",
  messagingSenderId: "757888333827",
  appId: "1:757888333827:web:1703a8f4322697beb53636",
  measurementId: "G-8RFFJLVZEB"
};

(self as any).firebase.initializeApp(firebaseConfig);
const messaging = (self as any).firebase.messaging();

messaging.onBackgroundMessage((payload: any) => {
  console.log('[sw.ts] Received background message ', payload);
  
  const title = payload.notification?.title || 'GastosApp';
  const options = {
    body: payload.notification?.body || 'Tienes una nueva notificación.',
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg',
    data: payload.data?.url || '/',
    vibrate: [100, 50, 100],
  };

  self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  if (event.notification.data) {
    event.waitUntil(
      self.clients.openWindow(event.notification.data)
    );
  }
});

